In [1]:
import pandas as pd
import numpy as np
import time
import matplotlib.pyplot as plt
import gensim
from gensim.models.doc2vec import Doc2Vec
from gensim.test.utils import get_tmpfile
from nltk.tokenize import word_tokenize

import vg_recommender_driver as file_vg
import data_pre_processing as file_dpp

C:\Users\ericw\anaconda3\lib\site-packages\gensim\similarities\__init__.py:15: UserWarning: The gensim.similarities.levenshtein submodule is disabled, because the optional Levenshtein package <https://pypi.org/project/python-Levenshtein/> is unavailable. Install Levenhstein (e.g. `pip install python-Levenshtein`) to suppress this warning.
  warnings.warn(msg)


In [2]:
model_prep_pack = file_vg.model_prep(use_num_clusters = True)

vg_all_content_train = model_prep_pack[0]
demo_dataframe = model_prep_pack[1]
demo_dataframe

(16593, 2)
(16713, 2)
(5516, 2)
Number of texts processed:  32779


name  \
0      LEVEL (Czech Republic)   
1                 GameCritics   
2           PC Games (Russia)   
3            Adventure Gamers   
4             Armchair Empire   
...                       ...   
32774              XboxAddict   
32775                    ICXM   
32776           Worth Playing   
32777        TrueAchievements   
32778                GameSpot   

                                                  review      game platform  \
0      Portal 2 is a masterpiece, a work of art that ...  portal 2       PC   
1      So do we need Portal 2? Do I need it? Maybe no...  portal 2       PC   
2      Portal 2 exceeds every expectation. It has a s...  portal 2       PC   
3      Like its predecessor, Portal 2 is not an adven...  portal 2       PC   
4      Pile on the "Oh, yes!" moments of solving some...  portal 2       PC   
...                                                  ...       ...      ...   
32774  Despite the lackluster quality with some of it...    ride 2     XOne   
32775  Ride 2 is a huge improvement over the original...    ride 2     XOne   
32776  Ride 2 is certainly an improvement over the or...    ride 2     XOne   
32777  Despite the addition of more bikes and tracks,...    ride 2     XOne   
32778  On paper, then, Ride 2 is an exciting proposit...    ride 2     XOne   

       score          date  Unnamed: 0      Name Platform  Year_of_Release  \
0      100.0  May 25, 2011        2703  portal 2       PC           2011.0   
1      100.0  May  8, 2011        2703  portal 2       PC           2011.0   
2      100.0  May  6, 2011        2703  portal 2       PC           2011.0   
3      100.0  Apr 29, 2011        2703  portal 2       PC           2011.0   
4      100.0  Apr 28, 2011        2703  portal 2       PC           2011.0   
...      ...           ...         ...       ...      ...              ...   
32774   70.0  Mar  7, 2017       16512    ride 2     XOne           2016.0   
32775   70.0  Feb 18, 2017       16512    ride 2     XOne           2016.0   
32776   65.0  Mar  9, 2017       16512    ride 2     XOne           2016.0   
32777   60.0  Oct 13, 2016       16512    ride 2     XOne           2016.0   
32778   40.0  Feb 24, 2017       16512    ride 2     XOne           2016.0   

       ... Critic_Count User_Score  User_Count        Developer  Rating  \
0      ...         52.0        8.8      5999.0   Valve Software    E10+   
1      ...         52.0        8.8      5999.0   Valve Software    E10+   
2      ...         52.0        8.8      5999.0   Valve Software    E10+   
3      ...         52.0        8.8      5999.0   Valve Software    E10+   
4      ...         52.0        8.8      5999.0   Valve Software    E10+   
...    ...          ...        ...         ...              ...     ...   
32774  ...          NaN        8.2         6.0  Milestone S.r.l       E   
32775  ...          NaN        8.2         6.0  Milestone S.r.l       E   
32776  ...          NaN        8.2         6.0  Milestone S.r.l       E   
32777  ...          NaN        8.2         6.0  Milestone S.r.l       E   
32778  ...          NaN        8.2         6.0  Milestone S.r.l       E   

       regional_sales_label  interval_years_2020  gloabl_sales_log  \
0                     NA&EU                0.875          0.434073   
1                     NA&EU                0.875          0.434073   
2                     NA&EU                0.875          0.434073   
3                     NA&EU                0.875          0.434073   
4                     NA&EU                0.875          0.434073   
...                     ...                  ...               ...   
32774                    EU                1.000          0.001000   
32775                    EU                1.000          0.001000   
32776                    EU                1.000          0.001000   
32777                    EU                1.000          0.001000   
32778                    EU                1.000          0.001000   



In [3]:
t = time.localtime()
current_time = time.strftime("%H:%M:%S", t)

#Parameters for Doc2Vec Model A
vector_size = 50
window = 5
min_count = 1
negative = 0
epoch = 10
param_list = [vector_size, window, min_count, negative, epoch]
print(current_time, "MODEL A TRAINING IN PROGRESS. PLEASE WAIT --- ")
d2v_model_demo_A = file_vg.get_doc2vec(vg_all_content_train, param_list)
t = time.localtime()
current_time = time.strftime("%H:%M:%S", t)
print(current_time, "MODEL A IS TRAINED AND READY:", "Vector Size:", vector_size, ";", "Epoch Number:", epoch)

14:58:54 MODEL A TRAINING IN PROGRESS. PLEASE WAIT --- 
14:59:30 MODEL A IS TRAINED AND READY: Vector Size: 50 ; Epoch Number: 10


In [4]:
t = time.localtime()
current_time = time.strftime("%H:%M:%S", t)

#Parameters for Doc2Vec Model B
vector_size = 100
window = 5
min_count = 1
negative = 0
epoch = 1000

param_list = [vector_size, window, min_count, negative, epoch]

print(current_time, "MODEL B TRAINING IN PROGRESS. PLEASE WAIT --- ")
d2v_model_demo_B = file_vg.get_doc2vec(vg_all_content_train, param_list)
t = time.localtime()
current_time = time.strftime("%H:%M:%S", t)
print(current_time, "MODEL B IS TRAINED AND READY:", "Vector Size:", vector_size, ";", "Epoch Number:", epoch)

14:59:30 MODEL B TRAINING IN PROGRESS. PLEASE WAIT --- 
15:28:45 MODEL B IS TRAINED AND READY: Vector Size: 100 ; Epoch Number: 1000


# BUFFER CELL
### MODELS Above 
### EXECUTIONS Below

### Run Job I: Fallout, 7 out of 10

In [5]:
file_vg.run_recommender(d2v_model_demo_A, demo_dataframe)

fallout
7.0
[6.2 6.5 5.4]
[10682, 19068, 14410, 27087, 21602, 9827, 3936, 14743, 7642, 19064]
[0.5659518241882324, 0.48661088943481445, 0.48263850808143616, 0.4796906113624573, 0.46791914105415344, 0.46771472692489624, 0.46480968594551086, 0.461399108171463, 0.4575643241405487, 0.45532774925231934]
 
Input game: fallout
Input user score: 7.0
Similarity - Recommended games
0.5659518241882324 - castlevania: lords of shadow - mirror of fate
0.48661088943481445 - fallout 4
0.48263850808143616 - danganronpa: trigger happy havoc
0.4796906113624573 - watch dogs 2
0.46791914105415344 - etrian mystery dungeon
0.46771472692489624 - the wonderful 101
0.46480968594551086 - bust-a-move universe
0.461399108171463 - wolfenstein: the new order
0.4575643241405487 - little deviants


In [6]:
file_vg.run_recommender(d2v_model_demo_B, demo_dataframe)

fallout
7.0
[6.2 6.5 5.4]
[13721, 8587, 19068, 12531, 29157, 29166, 28472, 20826, 16860, 9967]
[0.4247927665710449, 0.37954291701316833, 0.3587292730808258, 0.3517489433288574, 0.35068273544311523, 0.3506515920162201, 0.34178870916366577, 0.3393701910972595, 0.3381994664669037, 0.3378807008266449]
 
Input game: fallout
Input user score: 7.0
Similarity - Recommended games
0.4247927665710449 - call of duty: advanced warfare
0.37954291701316833 - saints row iv
0.3587292730808258 - fallout 4
0.3517489433288574 - titanfall
0.35068273544311523 - batman: arkham vr
0.3506515920162201 - quantum break
0.34178870916366577 - disgaea 5: alliance of vengeance
0.3393701910972595 - the lego movie videogame
0.3381994664669037 - call of duty: ghosts


### Run Job II: Elder Scrolls, 10 out of 10

In [10]:
file_vg.run_recommender(d2v_model_demo_A, demo_dataframe)

elder scrolls
10.0
[8.1 5.7]
[19938, 13249, 23088, 23185, 15580, 29594, 2142, 13566, 7280, 18535]
[0.5186320543289185, 0.5125606656074524, 0.5060069561004639, 0.5053179860115051, 0.5001996755599976, 0.4907010495662689, 0.4896400272846222, 0.4758257269859314, 0.4747908115386963, 0.469594806432724]
 
Input game: elder scrolls
Input user score: 10.0
Similarity - Recommended games
0.5186320543289185 - halo 5: guardians
0.5125606656074524 - donkey kong country: tropical freeze
0.5060069561004639 - ultra street fighter iv
0.5053179860115051 - lego jurassic world
0.5001996755599976 - metal gear solid v: ground zeroes
0.4907010495662689 - uefa euro 2016
0.4896400272846222 - magicka
0.4758257269859314 - fifa 15
0.4747908115386963 - lego harry potter: years 5-7
0.469594806432724 - destiny: the taken king


In [11]:
file_vg.run_recommender(d2v_model_demo_B, demo_dataframe)

elder scrolls
10.0
[8.1 5.7]
[30782, 18538, 24600, 32738, 4290, 10183, 13244, 2757, 12812, 82]
[0.4205424189567566, 0.39485156536102295, 0.38941490650177, 0.3856979310512543, 0.38257426023483276, 0.381220281124115, 0.3761630058288574, 0.37006914615631104, 0.365151971578598, 0.3524610698223114]
 
Input game: elder scrolls
Input user score: 10.0
Similarity - Recommended games
0.4205424189567566 - nights of azure
0.39485156536102295 - destiny: the taken king
0.38941490650177 - bladestorm: nightmare
0.3856979310512543 - berserk and the band of the hawk
0.38257426023483276 - zero escape: virtue's last reward
0.381220281124115 - dragon's crown
0.3761630058288574 - donkey kong country: tropical freeze
0.37006914615631104 - homefront
0.365151971578598 - halo: the master chief collection
0.3524610698223114 - the elder scrolls v: skyrim


### Run Job III: Fallout, 7 out of 10, Cluster Labels added

In [13]:
demo_dataframe["cluster_label"].value_counts()

22    7176
0     4235
9     3529
14    3305
26    3085
7     2417
5     2023
1     1732
15    1051
24     696
20     628
11     421
18     376
16     361
6      345
17     292
23     247
8      214
21     205
3      161
12     130
10     104
2       39
4        7
Name: cluster_label, dtype: int64

In [14]:
d2v_model_demo_Aplus = file_vg.append_col_to_d2v(d2v_model_demo_A, demo_dataframe["cluster_label"])
file_vg.run_recommender(d2v_model_demo_Aplus, demo_dataframe)

fallout
7.0
[6.2 6.5 5.4]
[17130, 2588, 13280, 142, 20693, 19764, 17146, 30528, 8314, 3213]
[452.6667298259433, 417.80239905699966, 415.1742186080212, 413.5948178381257, 411.16441776050266, 408.8852096269839, 407.01738937207955, 406.431081787982, 402.8078552291546, 402.7737875009308]
 
Input game: fallout
Input user score: 7.0
Similarity - Recommended games
452.6667298259433 - yoshi's new island
417.80239905699966 - pilotwings resort
415.1742186080212 - donkey kong country: tropical freeze
413.5948178381257 - super mario 3d land
411.16441776050266 - tearaway unfolded
408.8852096269839 - rocket league
407.01738937207955 - wwe 2k17
406.431081787982 - animal crossing: new leaf
402.8078552291546 - rayman 3d


In [15]:
d2v_model_demo_Bplus = file_vg.append_col_to_d2v(d2v_model_demo_B, demo_dataframe["cluster_label"])
file_vg.run_recommender(d2v_model_demo_Bplus, demo_dataframe)

fallout
7.0
[6.2 6.5 5.4]
[8452, 4490, 17112, 23790, 30485, 15087, 1904, 30412, 14839, 23765]
[528.392881829752, 524.9074810898633, 523.9467960177137, 520.861867612525, 520.0282891010096, 518.2749739923061, 516.8766807875778, 516.6509966651494, 516.2408872194902, 515.7017707709374]
 
Input game: fallout
Input user score: 7.0
Similarity - Recommended games
528.392881829752 - tearaway
524.9074810898633 - littlebigplanet ps vita
523.9467960177137 - yoshi's new island
520.861867612525 - mario party 10
520.0282891010096 - wwe 2k17
518.2749739923061 - mario golf: world tour
516.8766807875778 - bit.trip saga
516.6509966651494 - farming simulator 17
516.2408872194902 - littlebigplanet 3


### Run Job IV: Elder Scrolls, 10 out of 10, Cluster Labels added

In [16]:
file_vg.run_recommender(d2v_model_demo_Aplus, demo_dataframe)

elder scrolls
10.0
[8.1 5.7]
[17130, 2588, 13280, 142, 20693, 19764, 17146, 30528, 8314, 3213]
[452.66672107241874, 417.80244421016005, 415.17424772411425, 413.59492165226885, 411.1642554167789, 408.8852837912185, 407.0174567345581, 406.43107957289374, 402.80776190721923, 402.77384869428295]
 
Input game: elder scrolls
Input user score: 10.0
Similarity - Recommended games
452.66672107241874 - yoshi's new island
417.80244421016005 - pilotwings resort
415.17424772411425 - donkey kong country: tropical freeze
413.59492165226885 - super mario 3d land
411.1642554167789 - tearaway unfolded
408.8852837912185 - rocket league
407.0174567345581 - wwe 2k17
406.43107957289374 - animal crossing: new leaf
402.80776190721923 - rayman 3d


In [17]:
file_vg.run_recommender(d2v_model_demo_Bplus, demo_dataframe)

elder scrolls
10.0
[8.1 5.7]
[8452, 4490, 17112, 23790, 30485, 15087, 1904, 30412, 14839, 23765]
[528.3928193749155, 524.9073389441318, 523.9466776872566, 520.8618559839595, 520.0282774404648, 518.2749199524355, 516.8766012352529, 516.6509568949856, 516.2408551670653, 515.7016904614406]
 
Input game: elder scrolls
Input user score: 10.0
Similarity - Recommended games
528.3928193749155 - tearaway
524.9073389441318 - littlebigplanet ps vita
523.9466776872566 - yoshi's new island
520.8618559839595 - mario party 10
520.0282774404648 - wwe 2k17
518.2749199524355 - mario golf: world tour
516.8766012352529 - bit.trip saga
516.6509568949856 - farming simulator 17
516.2408551670653 - littlebigplanet 3
